'use client';

/**
 * Credits: who made CONTINUA, what it is built with, and where everything on
 * screen comes from. The team and its roles are the ones the proposal deck
 * gives (`deliverables/CONTINUA_Team_Kanban_Proposal.pptx`); the stack is the
 * one the manifests pin; the provenance lines repeat what the documents say.
 */

import Link from 'next/link';
import { AppShell } from './AppShell';
import { REPO_URL } from '@/lib/deployment';

const TEAM: readonly { initials: string; name: string; role: string; focus: string }[] = [
  {
    initials: 'AA',
    name: 'Awaiz Ahmed',
    role: 'Technical & Product Lead',
    focus: 'Leads architecture, model, integration, dashboard and pitch.',
  },
  {
    initials: 'MU',
    name: 'Mohammad Umar',
    role: 'Network & 5G Lead',
    focus: 'MPTCP, QoS, Linux routing and wireless systems.',
  },
  {
    initials: 'FJ',
    name: 'Fatima Jamal',
    role: 'Simulation & Experiment Lead',
    focus: 'Mininet-WiFi, tc netem, automation and statistics.',
  },
  {
    initials: 'HM',
    name: 'Huda Mueen',
    role: 'Research & Experience Lead',
    focus: 'Literature, usability, documentation and the demo narrative.',
  },
];

const STACK: readonly { group: string; items: readonly string[] }[] = [
  { group: 'Interface', items: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'] },
  { group: '3D', items: ['three.js', 'React Three Fiber', 'drei', 'Blender (every model, generated by script)', 'Draco mesh compression'] },
  { group: 'Engine', items: ['Python', 'FastAPI', 'Uvicorn', 'Pydantic', 'NumPy', 'scikit-learn'] },
  { group: 'Checks', items: ['Playwright', 'pytest', 'ESLint'] },
  {
    group: 'Film and voice',
    items: [
      'HyperFrames',
      'FFmpeg',
      'Chatterbox (the films’ narration)',
      'Kokoro-82M (the voice it speaks in)',
      'Windows speech (the voice in the app)',
      'Music: Happy Beats / Business Moves by ende.app (CC BY 4.0)',
      'Sound effects: Kenney (CC0)',
    ],
  },
  { group: 'Hosting', items: ['Cloudflare'] },
];

const doc = (path: string) => `${REPO_URL}/blob/main/${path}`;

export function CreditsView() {
  return (
    <AppShell>
      <div className="doc-scroll scroll-y h-full">
        <article className="doc">
          <header className="doc-hero glass">
            <div className="doc-kicker">Credits</div>
            <h1 className="doc-title">
              Made by <span className="brand-text">Team Kanban</span>
            </h1>
            <p className="doc-lede">
              CONTINUA - Predictive Network Continuity. The network changes; the session doesn&apos;t. Built for the EDGE
              challenge of Advanced Technology Pioneers 2026.
            </p>
          </header>

          <section aria-labelledby="team-title" className="doc-section">
            <h2 id="team-title" className="doc-h2">
              The team
            </h2>
            <ul className="credits-team">
              {TEAM.map((member) => (
                <li key={member.name} className="credits-member glass">
                  <span className="credits-avatar" aria-hidden>
                    {member.initials}
                  </span>
                  <div className="min-w-0">
                    <strong className="credits-name">{member.name}</strong>
                    <span className="credits-role">{member.role}</span>
                    <p className="credits-focus">{member.focus}</p>
                  </div>
                </li>
              ))}
            </ul>
          </section>

          <section aria-labelledby="stack-title" className="doc-section">
            <h2 id="stack-title" className="doc-h2">
              Built with
            </h2>
            <div className="credits-stack glass">
              {STACK.map((entry) => (
                <div key={entry.group} className="credits-stack-row">
                  <span className="section-label">{entry.group}</span>
                  <ul>
                    {entry.items.map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
            <p className="doc-footnote">With thanks to the people who build and maintain every one of them.</p>
          </section>

          <section aria-labelledby="sources-title" className="doc-section">
            <h2 id="sources-title" className="doc-h2">
              Where everything comes from
            </h2>
            <ul className="doc-scope glass">
              <li>
                <strong>Every run</strong> on this site was produced by the CONTINUA engine, in simulation, and is replayed here.
                No live network was measured.
              </li>
              <li>
                <strong>Every model</strong> - the rover, the island, the masts - is generated by a script in the repository;
                nothing was bought or downloaded. The one third-party runtime file is Google&apos;s Draco decoder (Apache-2.0).
              </li>
              <li>
                <strong>The voices are synthetic.</strong> The lines the app says aloud were recorded on the development machine
                with a voice that ships with Windows. The project&apos;s demo films are narrated by the open-weight Chatterbox
                model, run locally, in a voice taken from the open Kokoro-82M model&apos;s stock voice - not a real
                person&apos;s - and every take was transcribed and checked against the script.
              </li>
              <li>
                <strong>The challenge question</strong> is the EDGE challenge statement&apos;s own. The references analysed are
                IETF RFC 8684 (Multipath TCP) and 3GPP TS 23.501 / TS 24.193 (ATSSS).
              </li>
            </ul>
            <p className="doc-footnote">
              <a href={REPO_URL} target="_blank" rel="noreferrer">
                Source code
              </a>{' '}
              ·{' '}
              <a href={doc('docs/AI_USE.md')} target="_blank" rel="noreferrer">
                How AI is - and is not - used
              </a>{' '}
              ·{' '}
              <a href={doc('docs/ASSET_MANIFEST.md')} target="_blank" rel="noreferrer">
                Asset manifest
              </a>{' '}
              · <Link href="/challenge">The brief, answered</Link>
            </p>
          </section>
        </article>
      </div>
    </AppShell>
  );
}
