/**
 * Content hashes of the runtime models, appended to their URLs as `?v=`.
 * Generated by scripts/blender (continua_lib.write_model_versions) after
 * every export - do not edit by hand.
 */
export const MODEL_VERSIONS = {
  rover: 'ae48ad0cac03',
  roverLod1: '7fbd74f1e7a9',
  props: 'e4bf6b2d6426',
  dockTwo: 'f141c709d4db',
  tunnel: 'b27b11cf4415',
} as const;
