/**
 * Content hashes of the runtime models, appended to their URLs as `?v=`.
 * Generated by scripts/blender (continua_lib.write_model_versions) after
 * every export - do not edit by hand.
 */
export const MODEL_VERSIONS = {
  rover: '1f249efe38c2',
  roverLod1: 'a9e8b5a86436',
  props: '1e304d0c615e',
} as const;
